### ISSUE TITLE
linux don't work copy function

### ISSUE THREAD

**Issue by snajperro** [DimensionalDevelopment/Rift#24]
`:/home/files/trash$ java -jar Rift-1.0.3-45.jar 
Gtk-Message: 13:44:05.441: Failed to load module "canberra-gtk-module"
java.nio.file.NoSuchFileException: home/files/trash/Rift-1.0.3-45.jar
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at org.dimdev.riftloader.Main.runClientInstaller(Main.java:153)
	at org.dimdev.riftloader.Main.main(Main.java:29)
`

**Comment by UpcraftLP** [comment]
um... it says that it cannot find the rift jar, lol

**Comment by Janrupf** [comment]
Its pretty funny what happens here... note the missing / before home.
