### ISSUE TITLE
Can not start server

### ISSUE THREAD

**Issue by MSandro** [DimensionalDevelopment/Rift#33]
I am not able to start a server with Rift-1.0.4-63.jar.

How to reproduce:
* Download the jar file and put it in an empty folder
* java -jar Rift-1.0.4-63.jar --server

Log:
File 'server.jar' does not exist

```
Choose which server you'd like to download:
  1) Vanilla
Choice: 1
Downloading server jar: https://launcher.mojang.com/mc/game/1.13/server/d0caafb8438ebd206f99930cfaecfa6c9a13dca0/server.jar
Downloading library: https://www.dimdev.org/maven/org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar
Exception in thread "main" java.net.UnknownHostException: www.dimdev.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at java.net.URL.openStream(URL.java:1045)
        at org.dimdev.riftloader.Main.getOrDownload(Main.java:77)
        at org.dimdev.riftloader.Main.main(Main.java:56)

* java -jar Rift-1.0.4-63.jar --server

Logs:
Downloading library: https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/6.2/asm-commons-6.2.jar
Exception in thread "main" java.net.UnknownHostException: repo1.maven.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at java.net.URL.openStream(URL.java:1045)
        at org.dimdev.riftloader.Main.getOrDownload(Main.java:77)
        at org.dimdev.riftloader.Main.main(Main.java:56)
```

Java:
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

What is wrong? Should I update Java?

**Comment by Runemoro** [comment]
`java.net.UnknownHostException: www.dimdev.org`
`java.net.UnknownHostException: repo1.maven.org`

Seems to be a network problem, not a Rift problem. If you try to open those in a browser, does it work?

**Comment by MSandro** [comment]
curl www.dimdev.org
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.12.1 (Ubuntu)</center>
</body>
</html>

**Comment by MSandro** [comment]
'''Launching server...
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
        at org.dimdev.riftloader.Main.main(Main.java:64)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
root@mc-113-p8tmg:/usr/src/myapp# cd test/
root@mc-113-p8tmg:/usr/src/myapp/test# java -jar Rift-1.0.4-63.jar --server
Downloading library: https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/6.2/asm-tree-6.2.jar
Downloading library: https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
Launching server...
[18:52:22] [main/INFO]: Loading tweak class name org.dimdev.riftloader.launch.RiftLoaderServerTweaker
[18:52:22] [main/INFO]: Using primary tweak class name org.dimdev.riftloader.launch.RiftLoaderServerTweaker
[18:52:22] [main/INFO]: Calling tweak class org.dimdev.riftloader.launch.RiftLoaderServerTweaker
[18:52:22] [main/INFO]: Searching mods on classpath
[18:52:22] [main/INFO]: Loaded mod 'rift'
[18:52:22] [main/INFO]: Searching for mods in mods
[18:52:22] [main/INFO]: Loaded 1 mods
[18:52:22] [main/INFO]: Initializing mods
[18:52:22] [main/INFO]: Loading Rift!
[18:52:22] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:28) ~[Rift-1.0.4-63.jar:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at org.dimdev.riftloader.Main.main(Main.java:64) [Rift-1.0.4-63.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[Rift-1.0.4-63.jar:?]
        ... 3 more
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/asm/launch/MixinBootstrap
        at org.dimdev.rift.Rift.onInitialization(Rift.java:15) ~[Rift-1.0.4-63.jar:?]
        at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:189) ~[Rift-1.0.4-63.jar:?]
        at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:54) ~[Rift-1.0.4-63.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[Rift-1.0.4-63.jar:?]
        ... 3 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinBootstrap
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
        at org.dimdev.rift.Rift.onInitialization(Rift.java:15) ~[Rift-1.0.4-63.jar:?]
        at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:189) ~[Rift-1.0.4-63.jar:?]
        at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:54) ~[Rift-1.0.4-63.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[Rift-1.0.4-63.jar:?]
        ... 3 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
        at org.dimdev.rift.Rift.onInitialization(Rift.java:15) ~[Rift-1.0.4-63.jar:?]
        at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:189) ~[Rift-1.0.4-63.jar:?]
        at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:54) ~[Rift-1.0.4-63.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[Rift-1.0.4-63.jar:?]
        ... 3 more

**Comment by Runemoro** [comment]
Yes, use the latest curseforge build for now. The latest dev version doesn't work.

**Comment by MSandro** [comment]
I got it working.
No idea why various hostnames could not be resolved.I
