### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by E4002X3102** [DimensionalDevelopment/Rift#62]
Tried to get Rift working on Minecraft via both Minecraft Launcher and MultiMC launcher. At Minecraft Launcher I got 'GAME CRASH:An unexpected issue occurred and the game has crashed. We are sorry for the inconvenience.' without giving me any error log. When I set up Rift instance on MultiMC I got the following error log. I am running on Ubuntu 18.10, but I tried on Windows 10(dual boot) as well and also can't launch.
MultiMC version: 0.6.2-1137

Minecraft folder is:
/home/burner/.local/share/multimc/instances/1.131/.minecraft

Java path is:
/usr/lib/jvm/java-11-openjdk-amd64/bin/java

Java is version 11.0.1, using 64-bit architecture.

Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)

Subsystem: ASUSTeK Computer Inc. Skylake GT2 [HD Graphics 520]

Kernel driver in use: i915

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/burner/.local/share/multimc/instances/1.131/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  /home/burner/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
  /home/burner/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar
  /home/burner/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar
  /home/burner/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
  /home/burner/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
  /home/burner/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
  /home/burner/.local/share/multimc/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /home/burner/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/burner/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/burner/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/burner/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/burner/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/burner/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/burner/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/burner/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/burner/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/burner/.local/share/multimc/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /home/burner/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/burner/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/burner/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/burner/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/burner/.local/share/multimc/libraries/com/mojang/brigadier/0.1.27/brigadier-0.1.27.jar
  /home/burner/.local/share/multimc/libraries/com/mojang/datafixerupper/1.0.16/datafixerupper-1.0.16.jar
  /home/burner/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/burner/.local/share/multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /home/burner/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/burner/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/burner/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/burner/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/burner/.local/share/multimc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /home/burner/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /home/burner/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /home/burner/.local/share/multimc/libraries/com/mojang/realms/1.13.4/realms-1.13.4.jar
  /home/burner/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /home/burner/.local/share/multimc/libraries/org/dimdev/rift/1.0.4-66/rift-1.0.4-66.jar
  /home/burner/.local/share/multimc/libraries/org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar
  /home/burner/.local/share/multimc/libraries/org/ow2/asm/asm/6.2/asm-6.2.jar
  /home/burner/.local/share/multimc/libraries/org/ow2/asm/asm-commons/6.2/asm-commons-6.2.jar
  /home/burner/.local/share/multimc/libraries/org/ow2/asm/asm-tree/6.2/asm-tree-6.2.jar
  /home/burner/.local/share/multimc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/burner/.local/share/multimc/libraries/com/mojang/minecraft/1.13/minecraft-1.13-client.jar

Native libraries:
  /home/burner/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6-natives-linux.jar
  /home/burner/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6-natives-linux.jar
  /home/burner/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-linux.jar
  /home/burner/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6-natives-linux.jar
  /home/burner/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6-natives-linux.jar
  /home/burner/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6-natives-linux.jar
  /home/burner/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar

Params:
  --username  --version MultiMC5 --gameDir /home/burner/.local/share/multimc/instances/1.131/.minecraft --assetsDir /home/burner/.local/share/multimc/assets --assetIndex 1.13 --uuid  --accessToken  --userType  --versionType release --tweakClass org.dimdev.riftloader.launch.RiftLoaderClientTweaker

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 2617

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code 255.
Clipboard copy at: 10 Nov 2018 19:34:41 +0800

**Comment by 0f-0b** [comment]
Do not use Java 11; use Java 8 instead.
