### ISSUE TITLE
Crash with HalfLogs

### ISSUE THREAD

**Issue by Blackcorns** [DimensionalDevelopment/Rift#64]
when i try to start my minecraft
[21:02:16] [main/INFO]: Loading tweak class name org.dimdev.riftloader.launch.RiftLoaderClientTweaker
[21:02:16] [main/INFO]: Using primary tweak class name org.dimdev.riftloader.launch.RiftLoaderClientTweaker
[21:02:16] [main/INFO]: Calling tweak class org.dimdev.riftloader.launch.RiftLoaderClientTweaker
[21:02:16] [main/INFO]: Searching mods on classpath
[21:02:16] [main/INFO]: Loaded mod 'rift'
[21:02:16] [main/INFO]: Searching for mods in /home/billy/.minecraft/mods
[21:02:16] [main/INFO]: Loaded mod 'halflogs'
[21:02:16] [main/INFO]: Loaded 2 mods
[21:02:16] [main/INFO]: Initializing mods
[21:02:16] [main/INFO]: Loading Rift!
[21:02:17] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/home/billy/.minecraft/libraries/org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[21:02:17] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[21:02:17] [main/INFO]: Compatibility level set to JAVA_8
[21:02:17] [main/INFO]: Done initializing mods
[21:02:17] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:02:17] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:02:17] [main/INFO]: A re-entrant transformer 'org.dimdev.riftloader.RiftAccessTransformer' was detected and will no longer process meta class data
[21:02:17] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:02:17] [main/INFO]: Setting user: billy
[21:02:18] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockSlab
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_171]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:248) ~[RiftLoader.class:?]
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:233) ~[RiftLoader.class:?]
	at bcj.handler$onRegisterBlocks$zzc000(SourceFile:1829) ~[bcj.class:?]
	at bcj.t(SourceFile:1749) ~[bcj.class:?]
	at pf.c(SourceFile:460) ~[pf.class:?]
	at cfi.<init>(SourceFile:367) ~[cfi.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockSlab
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_171]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:248) ~[RiftLoader.class:?]
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:233) ~[RiftLoader.class:?]
	at bcj.handler$onRegisterBlocks$zzc000(SourceFile:1829) ~[bcj.class:?]
	at bcj.t(SourceFile:1749) ~[bcj.class:?]
	at pf.c(SourceFile:460) ~[pf.class:?]
	at cfi.<init>(SourceFile:367) ~[cfi.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_171]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:248) ~[RiftLoader.class:?]
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:233) ~[RiftLoader.class:?]
	at bcj.handler$onRegisterBlocks$zzc000(SourceFile:1829) ~[bcj.class:?]
	at bcj.t(SourceFile:1749) ~[bcj.class:?]
	at pf.c(SourceFile:460) ~[pf.class:?]
	at cfi.<init>(SourceFile:367) ~[cfi.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[Main.class:?]
	... 6 more
[21:02:18] [org.jackhuang.hmcl.event.EventBus.fireEvent/INFO] ProcessExitedAbnormallyEvent [source=org.jackhuang.hmcl.launch.ExitWaiter@1166038f, process=ManagedProcess[commands=[/home/billy/Applications/lib/jdk1.8.0_171/jre/bin/java, -Dminecraft.client.jar=/home/billy/.minecraft/versions/1.13/1.13.jar, -Duser.home=/home/billy, -XX:+UnlockExperimentalVMOptions, -XX:+UseG1GC, -XX:G1NewSizePercent=20, -XX:G1ReservePercent=20, -XX:MaxGCPauseMillis=50, -XX:G1HeapRegionSize=16M, -XX:-UseAdaptiveSizePolicy, -XX:-OmitStackTraceInFastThrow, -Xmn128m, -Xmx1920m, -Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Djava.library.path=/tmp/minecraft8179283909476343652, -Dminecraft.launcher.brand=HMCL, -Dminecraft.launcher.version=3.2.104, -cp, /home/billy/.minecraft/libraries/org/dimdev/rift/1.0.4-87/rift-1.0.4-87.jar:/home/billy/.minecraft/libraries/org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar:/home/billy/.minecraft/libraries/org/ow2/asm/asm/6.2/asm-6.2.jar:/home/billy/.minecraft/libraries/org/ow2/asm/asm-commons/6.2/asm-commons-6.2.jar:/home/billy/.minecraft/libraries/org/ow2/asm/asm-tree/6.2/asm-tree-6.2.jar:/home/billy/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar:/home/billy/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:/home/billy/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/home/billy/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:/home/billy/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/home/billy/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/home/billy/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/home/billy/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/home/billy/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/home/billy/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/home/billy/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/home/billy/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:/home/billy/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/home/billy/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/billy/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/home/billy/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/billy/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/home/billy/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/home/billy/.minecraft/libraries/com/mojang/brigadier/0.1.27/brigadier-0.1.27.jar:/home/billy/.minecraft/libraries/com/mojang/datafixerupper/1.0.16/datafixerupper-1.0.16.jar:/home/billy/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/home/billy/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar:/home/billy/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/home/billy/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/home/billy/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/billy/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/home/billy/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar:/home/billy/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:/home/billy/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:/home/billy/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar:/home/billy/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar:/home/billy/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar:/home/billy/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar:/home/billy/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar:/home/billy/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar:/home/billy/.minecraft/libraries/com/mojang/realms/1.13.0/realms-1.13.0.jar:/home/billy/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar:/home/billy/.minecraft/versions/1.13/1.13.jar, net.minecraft.launchwrapper.Launch, --username, billy, --version, HMCL 3.2.104, --gameDir, /home/billy/.minecraft, --assetsDir, /home/billy/.minecraft/assets, --assetIndex, 1.13, --uuid, 287b4c620c823caf8f413160f90df690, --accessToken, bb24cc386ddf403384e97e7ae6954ac0, --userType, mojang, --versionType, release, --width, 854, --height, 480, --tweakClass, org.dimdev.riftloader.launch.RiftLoaderClientTweaker], isRunning=true]] gets fired
[21:02:18] [org.jackhuang.hmcl.event.EventBus.fireEvent/INFO] ProcessStoppedEvent [source=org.jackhuang.hmcl.launch.ExitWaiter@1166038f] gets fired
[21:02:19] [org.jackhuang.hmcl.Launcher.stopWithoutPlatform/INFO] Stopping application without JavaFX Toolkit.
	at java.lang.Thread.getStackTrace(Thread.java:1559)
	at org.jackhuang.hmcl.Launcher.stopWithoutPlatform(Launcher.java:115)
	at org.jackhuang.hmcl.game.LauncherHelper.lambda$checkExit$27(LauncherHelper.java:369)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

[21:02:19] [org.jackhuang.hmcl.task.Schedulers.shutdown/INFO] Shutting down executor services.
Scene.DnDGesture.processDropEnd() - UNEXPECTD - source is NULL

**Comment by Blackcorns** [comment]
I use hmcl

**Comment by Blackcorns** [comment]
I found that rift crashes with all rift mod with the similar output,but if i only load rift ,it doesn't crash.
Forge for 1.12.2 doesn't crash either.
I am using the latest rift release with 1.13
java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by l89669** [comment]
I guess the mod you use is not obfusecated correctly, did you build the mod by yourself?

**Comment by Blackcorns** [comment]
> I guess the mod you use is not obfusecated correctly, did you build the mod by yourself?

Yeah,I build HalfLogs by myself
