### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by WcaleNieFritz** [DimensionalDevelopment/Rift#67]
(Linux OS)

LOGS:
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[16:01:23] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[16:01:23] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[16:01:23] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
[16:01:23] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more

**Comment by ZombieHDGaming** [comment]
This doesn't even mention Rift (which it should), so I can only assume this is a different issue than just Rift.

**Comment by WcaleNieFritz** [comment]
Yeah...this crash is when i have Rift version...

**Comment by Chocohead** [comment]
Are you using the old or new vanilla launcher when you get this?

**Comment by WcaleNieFritz** [comment]
Of course new, otherwise I could not turn on version 1.13. I do not know why in the jump pops 1.12 ... I came here to find out ... but as the moderator thinks ... "This does not even mention Rift" although the crash shows to me when I turn on the rift

**Comment by ZombieHDGaming** [comment]
@WcaleNieFritz If it had to do with Rift, it would mention the Rift like in this comment with the Rift Client Tweaker being at the top: https://github.com/DimensionalDevelopment/Rift/issues/57#issuecomment-439498889

Based on that, Rift is not at fault and is attempting to launch vanilla instead. Is your Rift properly installed?

**Comment by WcaleNieFritz** [comment]
Since the installer says that Rift has been installed correctly, it is rather so, all the files are in place in .minecraft

**Comment by Chocohead** [comment]
You say of course new, but the old jar launcher is capable of launching 1.13 (and Rift for that matter) too. The Rift installer doesn't insert `"minimumLauncherVersion": 21` into the profiles however which can cause issues like this where they don't load properly and completely miss everything off the classpath. This is almost certainly what you're seeing.

You could try going to `~/.minecraft/versions/1.13-rift-1.0.4-77` and opening `1.13-rift-1.0.4-77.json` with notepad (accounting for which ever Rift version you're using), then adding `"minimumLauncherVersion": 21,` onto the second line. So it would go from 
```
{
  "inheritsFrom": "1.13",
  "id": "1.13-rift-1.0.4-77",
  ...
```
to
```
{
  "inheritsFrom": "1.13",
  "minimumLauncherVersion": 21,
  "id": "1.13-rift-1.0.4-77",
  ...
```
So long as you've got the Minecraft launcher closed before you save, the Rift profile should then launch fine.

**Comment by WcaleNieFritz** [comment]
After adding the line code, the same goes on, the same crash content is displayed :/

EDIT: 

Ok, everything is working. I just downloaded version "v1.0.4-87" from here "https://github.com/DimensionalDevelopment/Rift/releases" and everything works, thanks for help;)
