### ISSUE TITLE
Minecraft not start with Rift-1.0.4-66 

### ISSUE THREAD

**Issue by Architect46** [DimensionalDevelopment/Rift#69]
i did refresh install and still same 

[12:44:56] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[12:44:56] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[12:44:56] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
[12:44:56] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by Iteries** [comment]
question:  Are you using a liteloader or MultiMC?
