### ISSUE TITLE
Game crashes upon startup

### ISSUE THREAD

**Issue by i1000** [DimensionalDevelopment/Rift#75]
I am using the latest rift, which appears to only be 1.13, and the latest easier villager trading mod, which is 1.13.2. Game crashes upon startup every time. Is there a rift for 1.13.2?

**Comment by Iteries** [comment]
Q: Are you using Optfine or MultiMC?  Reason need to more more detailed on what modifications you use.

**Comment by strongstancer** [comment]
I am using rift-1.0.4-SNAPSHOT with OptiFine 1.13.3_HD_U_E5. It worked all really well until today where I keep getting crash on startup saying `The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: net/optifine/CustomColors`
I did not change anything. That is why I don't get, why it suddenly stopped working. Tried rift-1.0.4-106 but it does not work too.

Removing Optifine will work, as error indicates.

A friend of mine got exactly the same problem with the same versions of rift and OptiFine.

**Comment by trgwii** [comment]
I got this exact same problem with the same versions today as well, on 2 computers. It was working fine until today, the setup hasn't changed. Looks like something has changed / been updated in the launcher that crashes this. Using OptiFine and VoxelMap. Removing OptiFine makes it run fine, using OptiFine without Rift also works.

Game version: 1.13.2
[Rift version](https://jitpack.io/com/github/Chocohead/Rift/jitpack-SNAPSHOT/Rift-jitpack-SNAPSHOT.jar) (Gets stored as Rift-jitpack-2cb118e6e0-1.jar)
OptiFine version: OptiFine 1.13.2 HD U E5
Java version:
```
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```
Windows version: 10.0.17134

**Comment by lukaskleinrensing** [comment]
I also got the same problem like trgwii when I startet the minecraftlauncher a few hours ago.
I'm running Optifine 1.13.2 HD U E5 (tried E4 as well) and VoxelMap 1.8.2 on MacOS 10.14.3 with Java RE build 1.8.0_144-b01.

> Removing OptiFine makes it run fine, using OptiFine without Rift also works.

Also agree with trgwii in this point

**Comment by sykefu** [comment]
Having the same problem, started today trying to run rift with optifine causes an error, Happens to me and 3 friends for who everything worked fine yesterday too:

java.lang.NoClassDefFoundError: net/optifine/CustomColors
	at net.optifine.util.TextureUtils.resourcesReloaded(TextureUtils.java:320)
	at net.optifine.util.TextureUtils$1.a(TextureUtils.java:367)
	at vh.a(SourceFile:118)
	at net.optifine.util.TextureUtils.registerResourceListener(TextureUtils.java:371)
	at cty.frameInit(EntityRenderer.java:1995)
	at cty.a(EntityRenderer.java:951)
	at cft.c(SourceFile:850)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Chi-Yu** [comment]
I can confirm this. It really just started failing today without any changes done on my end whatsoever.

> java.lang.NoClassDefFoundError: net/optifine/CustomColors

**Comment by primmysprinkles** [comment]
I am using RIFT 1.13 1.0.4-66.
Problems started occuring today, fine yesterday
When i run with VOXELMAP 1.8.2 the game crashes at startup
When I run RIFT alone, i can access single player world but accessing multiplayer servers "Outdated Client"
Checked and am using the most recent RIFT
