### ISSUE TITLE
Can't work for 1.13.2 with 1.0.4-106

### ISSUE THREAD

**Issue by ikarosu** [DimensionalDevelopment/Rift#79]
```
Launching server...
[00:00:58] [main/INFO]: Loading tweak class name org.dimdev.riftloader.launch.RiftLoaderServerTweaker
[00:00:58] [main/INFO]: Using primary tweak class name org.dimdev.riftloader.launch.RiftLoaderServerTweaker
[00:00:58] [main/INFO]: Calling tweak class org.dimdev.riftloader.launch.RiftLoaderServerTweaker
[00:00:58] [main/INFO]: Searching mods on classpath
[00:00:58] [main/INFO]: Loaded mod 'rift'
[00:00:58] [main/INFO]: Searching for mods in mods
[00:00:58] [main/INFO]: Loaded 1 mods
[00:00:58] [main/INFO]: Initializing mods
[00:00:58] [main/INFO]: Loading Rift!
[00:00:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/O:/mc_server/minecraft_server1.13Rift/libs/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[00:00:58] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[00:00:58] [main/INFO]: Compatibility level set to JAVA_8
[00:00:58] [main/INFO]: Adding new token provider org.dimdev.rift.Rift$RiftTokens to MixinEnvironment[DEFAULT]
[00:00:58] [main/INFO]: Done initializing mods
[00:00:58] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[00:00:58] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[00:00:59] [main/INFO]: A re-entrant transformer 'org.dimdev.riftloader.RiftAccessTransformer' was detected and will no longer process meta class data
[00:00:59] [main/FATAL]: Mixin apply failed mixins.rift.core.json:MixinMinecraftServer -> net.minecraft.server.MinecraftServer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Shadow field r was not located in the target class net.minecraft.server.MinecraftServer. Using refmap mixins.rift.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field r was not located in the target class net.minecraft.server.MinecraftServer. Using refmap mixins.rift.refmap.json
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:563) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:263) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:268) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) [mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) [mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) [mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_191]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
        at java.lang.Class.forName(Unknown Source) [?:1.8.0_191]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at org.dimdev.riftloader.Main.main(Main.java:66) [Rift-1.0.4-106.jar:?]
org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.rift.core.json:MixinMinecraftServer] from phase [DEFAULT] in config [mixins.rift.core.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at org.dimdev.riftloader.Main.main(Main.java:66)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field r was not located in the target class net.minecraft.server.MinecraftServer. Using refmap mixins.rift.refmap.json
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:563)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:263)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:268)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
        ... 10 more
[00:00:59] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.server.MinecraftServer
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at org.dimdev.riftloader.Main.main(Main.java:66) [Rift-1.0.4-106.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        ... 7 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.rift.core.json:MixinMinecraftServer] from phase [DEFAULT] in config [mixins.rift.core.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        ... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field r was not located in the target class net.minecraft.server.MinecraftServer. Using refmap mixins.rift.refmap.json
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:563) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:263) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:268) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[mixin-0.7.11-SNAPSHOT.jar:0.7.11-SNAPSHOT+unknown-b0.git-unknown]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        ... 7 more
```

**Comment by DelKatey** [comment]
Use the 1.13.2 version here: https://github.com/Chocohead/Rift
